class CResultVal;
class CActSimBnd;
class CMemTable;
class CGridCell;
class CGridLyr;
class CSolver;
class CSsip;
class CPcg;
class CPressPeriod;
class CCHBCell;
class CGDWater;
class CBndCell;
class CPerBndData;
class CBndHandler;
class CSHBCell;
class CSHB;
class CRchgCell;
class CRchg;
class CWell;
class CRegion;
class CRegSche;
class CRegBudget;
class CLandSubCell;
class CLandSub;
class CMatZone;
class CCompSedmCell;
class CCoGrainCell;
class CCGSediment;
class CNDIntBedCell;
class CNDelayIntBed;
class CDIntBedCell;
class CDelayIntBed;
extern void PauAndQuit(void);
extern void TrimBlank(CString &str);
extern CGDWater GDWMOD;
using namespace std;